name: OTF Testing

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Functional Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create --driver bridge isolated

      - name: Deploy AUT
        run: docker build -t my-php-site:latest .

      - name: Run AUT
        run: docker run --network=isolated -d --name docker-apache my-php-site:latest

      - name: Set AUT URL
        run: echo "URL=http://docker-apache" >> $GITHUB_ENV

      - name: Check AUT Url (inside container)
        run: docker exec docker-apache curl -s http://localhost

      - name: Selenium Preparation
        run: docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name firefox-standalone selenium/standalone-firefox:latest

      - name: Wait for Selenium Hub
        run: sh wait.sh

      - name: Check the Hub
        run: curl http://localhost:4444/ui

      - name: Install Selenium Client
        run: pip install -U selenium

      - name: Run test
        run: python tests/hello_aut.py ${{ env.URL }}

      - name: Cleanup
        if: always()
        run: |
          docker rm -f docker-apache || true
          docker rm -f firefox-standalone || true
          docker network rm isolated || true
