name: OTF Testing

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  test:
    name: Functional Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build AUT
        run: docker build -t my-php-site:latest .

      - name: Run AUT
        run: docker run -p 8080:80 --name docker-apache -d my-php-site:latest

      - name: Wait AUT ready
        run: |
          for i in {1..20}; do
            if curl -sSf http://localhost:8080 > /dev/null; then
              echo "AUT ready"
              exit 0
            fi
            echo "Waiting AUT..."
            sleep 2
          done
          echo "AUT not ready"
          exit 1

      - name: Check AUT Url
        run: curl -v http://localhost:8080

      - name: Stop docker
        if: always()
        run: docker rm -f docker-apache
